version: '3.5'

services:

  api:
    image: node:17.6-alpine
    container_name: angular-pvnyyc
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules/:/node_modules
    ports:
      - "4200:4200"
      - "9876:9876"
    command: sh -c "npm install && npm run start"